pages:
  stage: deploy
  script:
#    - mvn clean package -U
#    - mv ./target/generated-docs/ public
    - echo 'crash on gitlab ci, using pages manually'
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master